version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - /app/backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

volumes:
  mongodb-data:
