version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  app:
    image: mindes/lecture_pass:latest
    container_name: miniapp
    volumes:
      - ./backend/.env:/app/backend/.env
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - APP_PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/miniapp
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

volumes:
  mongodb-data:
