name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        
      - name: Build the Docker image
        run: docker build -t mindes/lecture_pass:latest .

      - name: Push the Docker image to Docker Hub
        run: docker push mindes/lecture_pass:latest

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
          port: 22
          script: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            docker pull mindes/lecture_pass:latest
            
            echo "BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" > /app/backend/.env
            echo "APP_PORT=3000" >> /app/backend/.env

            if [ ! -s /app/backend/.env ]; then
              echo "Ошибка: .env файл пустой или не создан!" && exit 1
            fi

            docker-compose down || true
            docker-compose up -d --build
